# it doesn't matter what you do in here
# the only reason this exists is cause it keeps telling me to have a config file
# so yeah, do whatever you want, write something funny in here or something
# go ahead
#